import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1E1E91',
    padding: 8,
    paddingTop: 80,
  },
  backButton: {
    position: 'absolute',
    top: 40,
    left: 20,
    zIndex: 1,
  },
  pageTitle: {
    fontSize: 28,
    fontWeight: '600',
    color: 'white',
    textAlign: 'center',
    marginBottom: 15,
  },
  profileHeader: {
    alignItems: 'center',
    marginBottom: 15,
    backgroundColor: '#ffffff40',
    padding: 12,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#22E883',
    shadowColor: '#000',
    shadowOffset: {
      width: 0, height: 8,
    },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 5,
  },
  avatar: {
    width: 90,
    height: 90,
    borderRadius: 45,
    marginBottom: 8,
    borderWidth: 3,
    borderColor: '#22E883',
  },
  userName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'white',
    marginBottom: 4,
  },
  rank: {
    fontSize: 14,
    color: '#22E883',
  },
  profileDetails: {
    backgroundColor: '#ffffff40',
    padding: 12,
    borderRadius: 18,
    marginBottom: 25,
    borderWidth: 1,
    borderColor: '#333',
    shadowColor: '#000',
    shadowOffset: {
      width: 0, height: 8,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  detailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  text: {
    fontSize: 14,
    color: 'white',
    marginLeft: 6,
  },
  activitySection: {
    backgroundColor: '#ffffff40',
    padding: 12,
    borderRadius: 18,
    marginBottom: 25,
    borderWidth: 1,
    borderColor: '#333',
    shadowColor: '#000',
    shadowOffset: {
      width: 0, height: 8,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  sectionTitle: {
    fontSize: 16,
    color: 'white',
    fontWeight: 'bold',
    marginBottom: 6,
  },
  activityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  buttonsContainer: {
    marginBottom: 20,
    alignItems: 'center',
  },
  editButton: {
    flexDirection: 'row',
    backgroundColor: '#2266E8',
    width: 180,
    padding: 10,
    borderRadius: 30,
    marginBottom: 6,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#1C4A8B',
  },
  logoutButton: {
    flexDirection: 'row',
    backgroundColor: '#E82266',
    width: 180,
    padding: 10,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#B81F4F',
  },
  buttonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 6,
  },
});

export default styles;
